services:
  postgres:
    image: postgres:16
    container_name: sweeties_db
    environment:
      POSTGRES_DB: sweeties_db
      POSTGRES_USER: sweeties_user
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - sweeties_pgdata:/var/lib/postgresql/data
volumes:
  sweeties_pgdata:
